config/routes.rb
Rails.application.routes.draw do

  resources :users

  root                    'welcome#index'

  get 'blogposts'     =>  'articles#index'
  get 'res'           =>  'resources#_index'
  get 'cats'          =>  'categories#index'
  get 'about'         =>  'welcome#about'
  get 'contact'       =>  'welcome#contact'
  get 'projects'      =>  'welcome#projects'
  get 'tutorials'     =>  'welcome#tutorials'

  resources :articles do
    resources :comments
  end

  resources :categories

  resources :attachments

  resources :resources do
    resources :categories
  end

  resources :welcome do
    resources :articles
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

 # http_basic_authenticate_with name: "keckelmeyer", password: "abc123", except: [:index, :show]



  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
=begin
A couple of things to note. We use Article.find to
find the article we're interested in, passing in
params[:id] to get the :id parameter from the request.
We also use an instance variable (prefixed with @) to
hold a reference to the article object. We do this
because Rails will pass all instance variables to the
view.

Now, create a new file app/views/articles/show.html.erb
=end
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
=begin
We have to whitelist our controller parameters to
prevent wrongful mass assignment. In this case,
we want to both allow and require the title and
text parameters for valid use of create. The syntax
for this introduces require and permit.

This is often factored out into its own method so it
can be reused by multiple actions in the same controller,
for example create and update. Above and beyond mass
assignment issues, the method is often made private to
make sure it can't be called outside its intended
context. (see private below)

Then we create a model that will take our create
action and use it to put data into the database.

rake db:migrate will create the database, based
on the model just created.
=end
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
=begin
Here's what's going on: every Rails model can be
initialized with its respective attributes, which
are automatically mapped to the respective database
columns. In the first line we do just that
(remember that params[:article] contains the
attributes we're interested in). Then, @article.save
is responsible for saving the model in the database.
Finally, we redirect the user to the show action,
which we'll define later.

With the validation now in place, when you call
@article.save on an invalid article, it will return
false. If you open app/controllers/articles_controller.rb
again, you'll notice that we don't check the result of
calling @article.save inside the create action. If
@article.save fails in this situation, we need to show
the form back to the user.
=end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  http_basic_authenticate_with name: "PSERS", password: "2015", except: [:index, :show]

  def index
    @categories = Category.order(:name).all
  end

  def new
    @category=Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
    #@category = Category.find(params[:id], :order => "name")
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "PSERS", password: "2015", only: :destroy



  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
=begin
The destroy action will find the article we are looking at, locate the comment
within the @article.comments collection, and then remove it from the database and
send us back to the show action for the article.
=end


  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

=begin
You'll see a bit more complexity here than you did in the controller for articles.
That's a side-effect of the nesting that you've set up. Each request for a comment
has to keep track of the article to which the comment is attached, thus the initial
call to the find method of the Article model to get the article in question.

In addition, the code takes advantage of some of the methods available for an
association. We use the create method on @article.comments to create and save the
comment. This will automatically link the comment so that it belongs to that particular
article.

Once we have made the new comment, we send the user back to the original article using
the article_path(@article) helper. As we have already seen, this calls the show action
of the ArticlesController which in turn renders the show.html.erb template.
=end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  http_basic_authenticate_with name: "PSERS", password: "2015", except: [:_index, :show]
#

  def create
    @resource = Resource.new(resource_params)
    if @resource.save
      redirect_to @resource
    else
      render 'new'
    end
  end

  def new
    @resource = Resource.new
    @category_options = Category.order(:name).all.map{|c| [c.name]}
    #@category_options = Category.all.map{|c| [c.name, c.id]}
  end

  def _index
    @resources=Resource.order(:category, :title).all
    @resource_cat = @resources.group_by {|r| r.category}
  end

  def edit
    @resource = Resource.find(params[:id])
    @category_options = Category.all.map{|c| [c.name]}
  end

  def update
    @resource = Resource.find(params[:id])
    if @resource.update(resource_params)
      redirect_to @resource
    else
      render 'edit'
    end
  end

  def destroy
    @resource = Resource.find(params[:id])
    @resource.destroy
    redirect_to resource_path
  end

end

private
def resource_params
  params.require(:resource).permit(:category, :title, :link)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def resources
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
<!--The reason we can use this shorter, simpler form_for
declaration to stand in for either of the other forms is
that @article is a resource corresponding to a full set
of RESTful routes, and Rails is able to infer which URI
and method to use. For more information about this use
of form_for, see Resource-oriented style.-->
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text, :size => "70x10" %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path( :anchor =>"yield") %>
<table width=100% border="border-style: solid">
  <tr>
    <th width=25%>Title</th>
    <th >Text</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>
      <tr >
        <td class="title"><%= article.title %></td>
        <td><%= truncate(article.text, length: 200, omission: '... (continued)' ) %></td>
        <td width="10"><%= link_to 'Show', article_path(article, :anchor =>"yield") %></td>
        <td width="10"><%= link_to 'Edit', edit_article_path(article, :anchor =>"yield") %></td>
        <td width="10"><%= link_to 'Destroy', article_path(article),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
<!-- refactored the form into _form.html.erb partial -->
<%= render 'form' %>
<p>articles.new</p>
<%= link_to 'Back', articles_path( :anchor =>"yield") %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text.html_safe %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit Article', edit_article_path(@article, :anchor =>"yield") %> |
<%= link_to 'Back to Articles', articles_path( :anchor =>"yield") %>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/categories/edit.html.erb
<div class="title">
  <h2>Edit <span class="byline">an existing category</span></h2>
</div>
<%= render 'form' %>

<%= link_to 'Back', categories_path( :anchor =>"yield") %>

app/views/categories/index.html.erb
<div class="title">
  <h2>Categories <span class="byline">for resources</span></h2>
</div>
<%= link_to 'New Category', new_category_path( :anchor =>"yield") %>
<table>
  <tr>
    <th width="150">Name</th>
    <th colspan="3"></th>
  </tr>



  <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td width="10"><%= link_to 'Show', category_path(category, :anchor =>"yield") %></td>
        <td width="10"><%= link_to 'Edit', edit_category_path(category, :anchor =>"yield") %></td>
        <td width="10"><%= link_to 'Destroy', category_path(category),
                                   method: :delete,
                                   data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<div class="title">
  <h2>Add <span class="byline">a new resource category</span></h2>
</div>
<%= render 'form' %>
<%= link_to 'Back', categories_path(:anchor =>"yield") %>

app/views/categories/show.html.erb
<div class="title">
  <h2>See <span class="byline">current categories</span></h2>
</div>
<p>
  <strong>Title:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit Category', edit_category_path(@category, :anchor =>"yield") %> |
<%= link_to 'Back to Categories', categories_path( :anchor =>"yield") %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body, :size => "70x10" %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/_footer.html.erb
<p></p>
<hr>
<p>
<table >
  <tr>
    <td><%= link_to 'Home Page', root_path %></td>
    <td> | </td>
    <td><%= link_to 'Resources', resources_path( :anchor =>"yield") %></td>
  </tr>


</table>
<iframe align="right" src="
//z-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetAdHtml&ID=OneJS&OneJS=1&banner_type=setandforget&campaigns=holsetforget2&placement=assoc_banner_placement_default&region=US&marketplace=amazon&tracking_id=eckelmeyfamil-20&ad_type=banner&height=60&width=468&linkid=3ZXVBSGZCNUMGUIT&f=ifr
" width="468" height="60" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
<div class="alignright">
  <script type='text/javascript'>
      amzn_assoc_ad_type = 'banner';
      amzn_assoc_tracking_id = 'eckelmeyfamil-20';
      amzn_assoc_marketplace = 'amazon';
      amzn_assoc_region = 'US';
      amzn_assoc_placement = 'assoc_banner_placement_default';
      amzn_assoc_linkid = 'VKC5WI2U3EMLX56C';
      amzn_assoc_campaigns = 'holsetforget2';
      amzn_assoc_p = '26';
      amzn_assoc_banner_type = 'setandforget';
      amzn_assoc_width = '468';
      amzn_assoc_height = '60';
  </script>
  <script src='//z-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetScript&ID=OneJS&WS=1'></script>
</div>

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : WellFormed 
Description: A two-column, fixed-width design with dark color scheme.
Version    : 1.0
Released   : 20130731

-->
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Ruby on Rails Portfolio</title>

  <!--%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  = javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <%= csrf_meta_tags %>
  <!--[if IE 6]><link href="default_ie6.css" rel="stylesheet" type="text/css" /><![endif]-->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<div id="user_header">
  <%= link_to "Sign Up", new_user_path %>
</div>
<div id="logo" class="container">
  <h1><a href="#">Keith<span>Eckelmeyer</span></a></h1>
  <p>Ruby on Rails Project Portfolio</p>
</div>
<div id="menu" class="container">
    
  <div id="NavButton1" class="NavButton"><%= link_to 'HomePage', root_path %></div>
  <div id="NavButton2" class="NavButton"><%= link_to 'Tutorials', tutorials_path( :anchor =>"yield") %></div>
  <div id="NavButton3" class="NavButton"><%= link_to 'Projects', projects_path( :anchor =>"yield") %></div>
  <div id="NavButton4" class="NavButton"><%= link_to 'About', about_path( :anchor =>"yield") %></div>
  <div id="NavButton5" class="NavButton"><%= link_to 'Contact', contact_path( :anchor =>"yield") %></div>



</div>
<div id="banner" class="container">
  <!-- image_tag "pic01.jpg", size: "1200x500" %> -->
  <!--
  <img src="images/pic01.jpg" width="1200" height="500" alt="" /></div>
-->
  <div id="three-column" class="container">
  <div id="tbox1">
    <h2>Tutorials</h2>
    <p>Learn more about the tutorials I have completed and the ones I look to complete as part of my ongoing training.</p>
    <%= button_to 'Learn More', tutorials_path( :anchor =>"yield"), :class => "button", :method => :get %>
      </div>
  <div id="tbox2">
    <h2>Projects</h2>
    <p>The Rails projects I have done on my own, thanks to the tutorials, google, and the Ruby on Rails API reference. </p>
    <%= button_to 'Learn More', projects_path( :anchor =>"yield"), :class => "button", :method => :get %>
    <!-- <a href="#" class="button">Learn More</a>--> </div>
  <div id="tbox3">
    <h2></h2>
    <p></p>
    <a href="#" class="button"></a> </div>
</div>
<div id="page" class="container">
  <div id="content">

    <a name="yield"></a> <%= yield %>

  </div>
  <div id="sidebar">
    <h2 class="title">Latest Blog Entries</h2>
    <ul class="style2">
      <li class="first">
        <h3><%= link_to Article.order('id DESC').first.title, Article.order('id DESC').first %></h3>
        <p><%= link_to truncate(Article.order('id DESC').first.text, length: 100, omission: '... (continued)'), Article.order('id DESC').first %></p>
      </li>
      <li>
        <h3><%= link_to Article.order('id DESC').second.title, Article.order('id DESC').second %></h3>
        <p><%= link_to truncate(Article.order('id DESC').second.text, length: 100, omission: '... (continued)'), Article.order('id DESC').second %></p>
      </li>
      <li>
        <h3><%= link_to Article.order('id DESC').third.title, Article.order('id DESC').third %></h3>
        <p><%= link_to truncate(Article.order('id DESC').third.text, length: 100, omission: '... (continued)'), Article.order('id DESC').third %></p>

      </li>
    </ul>
  </div>
</div>
<div id="footer" class="container">
  <div id="fbox1">

      <script type='text/javascript'>
          amzn_assoc_ad_type = 'banner';
          amzn_assoc_tracking_id = 'eckelmeyfamil-20';
          amzn_assoc_marketplace = 'amazon';
          amzn_assoc_region = 'US';
          amzn_assoc_placement = 'assoc_banner_placement_default';
          amzn_assoc_linkid = 'XXBNSDXOI4TD3NQZ';
          amzn_assoc_campaigns = 'primemain';
          amzn_assoc_p = '12';
          amzn_assoc_banner_type = 'category';
          amzn_assoc_isresponsive = 'false';
          amzn_assoc_banner_id = '1N7QZYHSKNC8P06S6QG2';
          amzn_assoc_width = '300';
          amzn_assoc_height = '250';
      </script>
      <script src='//z-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetScript&ID=OneJS&WS=1'></script>


  </div>

  <div id="fbox2">

    <iframe src="
//z-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetAdHtml&ID=OneJS&OneJS=1&banner_type=setandforget&campaigns=holsetforget2&placement=assoc_banner_placement_default&region=US&marketplace=amazon&tracking_id=eckelmeyfamil-20&ad_type=banner&height=250&width=300&linkid=QFBAPSA7SWUTU7KZ&f=ifr
" width="300" height="250" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>


  </div>

  <div id="fbox3">
    <h2 class="title">Social</h2>
    <ul class="style1">
      <li class="first"><a href="https://twitter.com/KeithEckelmeyer">Twitter</a></li>
      <li><a href="https://www.facebook.com/keith.eckelmeyer">Facebook</a></li>
      <li><a href="https://plus.google.com/+KeithEckelmeyer">Google +</a></li>
      <li><a href="http://www.linkedin.com/pub/keith-a-eckelmeyer-mba/2a/103/823">LinkedIn</a></li>
    </ul>
  </div>
</div>
<div id="copyright" class="container">
  <p>&copy; Untitled. All rights reserved. | Photos by <a href="http://fotogrph.com/">Fotogrph</a> | Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>.</p>
</div>
</body>
</html>

app/views/resources/_form.html.erb
<%= form_for @resource do |f| %>
    <p>
      <%= f.label :category %><br>
      <%= f.select(:category, @category_options) %>
    </p>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :link %><br>
      <%= f.text_field :link %><br>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/resources/_index.html.erb
<div class="title">
  <h2>Resources <span class="byline">for developers</span></h2>
</div>
<p><%= link_to 'New Resource', new_resource_path( :anchor =>"yield") %></p>

<% @resource_cat.each do |category, resources| %>
    <%= category %><br>
    <% resources.each do |resource|%>
         - <%= link_to resource.title, resource.link %> |
        <%= link_to 'Edit', edit_resource_path(resource, :anchor =>"yield") %> |
        <%= link_to 'Destroy', resource_path(resource),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %><br>
    <% end %>
    <br>
<% end %>

app/views/resources/edit.html.erb
<div class="title">
  <h2>Edit <span class="byline">an existing resource</span></h2>
</div>
<%= render 'form' %>

<%= link_to 'Back', res_path(:anchor =>"yield") %>

app/views/resources/new.html.erb
<div class="title">
  <h2>Add <span class="byline">a new resource</span></h2>
</div>
<%= render 'form' %>
<%= link_to 'Back', res_path( :anchor =>"yield") %>
<%= link_to 'New Category', new_category_path( :anchor =>"yield") %>

app/views/resources/show.html.erb
<p>

  <strong>Category</strong>
</p>

<p>
  <strong>Name/Link</strong>

</p>

<%= link_to 'Back', res_path( :anchor =>"yield") %>

app/views/simple_interest_calc/_form.html.erb
<%= form_for @simple_interest_calc do |f| %>
    <p>
      <%= f.label :principle %><br>
      <%= f.text_field :principle %>
    </p>
    <p>
      <%= f.label :rate %><br>
      <%= f.text_field :rate %>
    </p>
    <p>
      <%= f.label :years %><br>
      <%= f.text_field :years %><br>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/welcome/about.html.erb
<div class="title">
  <h2>About <span class="byline">Keith</span></h2>
</div>
<p>Keith is a self described jack-of-all-trades. He has always been a tinkerer,
  interested in the inner workings of anything mechanical. As a child he would
  often take apart broken toys and attempt to fix them. This would later manifest
as building r/c cars, upgrading PC's,and fixing cars. </p>
<p>Never satisfied with what he was doing and always looking to learn more, he's
  worked a variety of jobs in different industries. He started out working at
  local restaurants and grocery stores then jumped to sales and customer service
  in retail. Playing with the latest in technology got him back into networking
  classes which took him down a path of supervisor, foreman, and project manager
  in IT infrastructure/construction.</p>
<p>From there Keith took on college starting at York College of Pennsylvania
  getting in his core studies, then transferring to University of Phoenix online
  - giving him the flexibility to continue his studies while also caring for his
  new born son... not to mention his continuation of accelerated learning. Keith
  completed his coursework and earned his BA in Information Technology in three years.</p>
<p>However, an IT job wasn't in the cards. After a brief stint in tech support,
  Keith found himself in logistics as a 3PL warehouse manager. From there, Keith started
and completed MBA coursework with Western Governors University, while providing IT input
and pushing senior management towards an electronic document system and away from paper
  record keeping as a whole.</p>
<p>In 2008, sales were slowing, manufacturing was halting, and inventories were shrinking.
  Keith found himself laid off.</p>
<p>Despite trying his best, jobs were scare and interviews even more so. In 2011, Keith
became an employee of the Commonwealth of Pennsylvania where he quickly put his analytical
 and problem solving skills to use as a management analyst. Since then, Keith has taken a
  management position as a business analyst and now is currently an applications developer.</p>
<p>Keith can be found working on his car, tossing the football around with his son, and learning Ruby on Rails.</p>

app/views/welcome/contact.html.erb
<div class="title">
  <h2>Contact <span class="byline">Keith</span></h2>
</div>
<p>The best way to contact me is via the LinkedIn link at the bottom right, or at
  <a href="mailto:keith.eckelmeyer@gmail.com">Keith.Eckelmeyer@gmail.com</a></p>
<p>I'm always looking for freelance work and am willing to volunteer my Ruby on Rails skills for non-profits.</p>

app/views/welcome/index.html.erb
<div class="title">
  <h2>Welcome <span class="byline">to my Rails portfolio</span></h2>
</div>
<p>Please feel free to check in periodically as I build onto this site with completed tutorials and my own practice apps.</p>
<p></p>

<!--
<body>
    <h1>Welcome</h1>
    <h2>Ruby on Rails Project Page</h2>
    <hr>
    <br>
    <p>Hello everyone and welcome to my adventure with Ruby on Rails!</p>
    <p>This site will house all of my Ruby on Rails projects.
      The first of which is the <%= link_to 'Blog', controller: 'articles' %>
      application from <a href="http://guides.rubyonrails.org/getting_started.html">
      RubyOnRails.org</a></p>
    <p>Future apps or enhancements I plan on developing are:</p>
    <ul>
      <li>User creation and authentication for my blog commenters
        (from a twitter clone app) </li>
      <li>A hangman game (from a tutorial)</li>
      <li>Web design enhances (some via CSS tutorials,
        some others from Bootstrap or Material Design)</li>
      <li>A few calculators, such as a basic, interest,
        and loan/amortization.</li>
      <li>And as a capstone project (and something near and dear to my heart),
        a database of ferret foods, ranking them using a previously developed
        scale based on the ingredients. </li>
    </ul>
    <br>
    <p>Feel free to check in periodically and see where I am at,
      what I have learn, and what tips I have to share for new Rails developers</p>
    <br>
    <p>My Apps:</p>
    <ul>
      <li><%= link_to 'My Blog', controller: 'articles' %></li>
      <li><%= link_to 'Resource Categories', controller: 'categories' %></li>
    </ul>

</body>
-->

app/views/welcome/projects.html.erb
<div class="title">
  <h2>Ruby on Rails <span class="byline">Projects</span></h2>
</div>

<p><%= link_to 'Resources', res_path( :anchor =>"yield") %></p>
<p><%= link_to 'Categories (for resources)', cats_path( :anchor =>"yield") %></p>
<p><%= link_to 'Simple Interest Calculator', calculate_path(:anchor =>"yield") %></p>
<p><a href="#">Ferret Kibble Database (future)</a></p>
<p><a href="#"></a></p>
<p><a href="#"></a></p>
<p><a href="#"></a></p>
<p><a href="#"></a></p>

app/views/welcome/resources.html.erb
<div class="title">
  <h2>Ruby on Rails <span class="byline">Projects</span></h2>
</div>
<p><%= link_to "Blog", blogposts_path( :anchor =>"yield") %></p>
<p><%= link_to "Developer Resources", res_path( :anchor =>"yield") %></p>
<p><%= link_to "Categories (For Developer Resources)", cats_path( :anchor =>"yield")  %></p>
<p>Ferret Kibble Database (future project)</p>